replicaCount: 1

image:
  repository: your-dockerhub-username/palindrome-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 9091

resources: {}
